import "./globals.css";
import Modal from "@/components/Modal/Modal";

export const metadata = {
  title: "Trello 2.0 AI Clone",
  description: "Generated by Or Assayag",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#f5f6f8]">
        <Modal />
        {children}
      </body>
    </html>
  );
}
